name: Second Workflow

on:
  # you need to fire/click to execute this event
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! Rhis is the first job

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Print to Log JavaScript
        id: print-to-log-js
        uses: actions/hello-world-javascript-action@main
        with:
          # this value is the same that the value $GITHUB_ACTOR
          who-to-greet: ${{ github.actor }}

      - name: time
        run : |
          echo "The time of the greeting wast at : ${{ steps.print-to-log-js.outputs.time }}"
        

  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: SecondJob Script
        shell: bash
        run: |
          echo this is the second job
          echo and this is  multi-line script

          
